version: '3.7'

services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongodb.local
    hostname: 'mongodb.local'
    user: 0:0
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27017:27017
    volumes:
    - /srv/mongo/data/db:/data/db
    networks:
      docker-apps-local:
        ipv4_address: "192.168.38.9"
    
networks:
  default:
    external:
      name: docker-apps-local
  docker-apps-local:
    external: true
